# Generated by Django 4.2.4 on 2023-08-12 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_ssh_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssh',
            name='pub_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
